#!/bin/bash
#CarrIOTA field Nodestatistics
#by Michi6383 & 0xDEADBEEF
#INSTALLATION AND HOW TO USE
#wget https://raw.githubusercontent.com/michi6383/field_statistics/master/field_statistics -O points.sh
#chmod +x points.sh
#./points.sh iota1.heidger.eu (replace iota1.heidger.eu with your name configured in field.ini)

nodename="$1"

#check for existence and get all statistics of your node
nodestats=$(curl -s https://field.carriota.com/api/v1/graph --insecure | jq ".[] | select(.field.name==\"$nodename\")")
echo ${nodestats} | grep -q ${nodename}
nodefound=$?
if [ "$nodefound" = "0" ];
  then
	echo Nodename: $nodename
	
	publicId=$(echo $nodestats | jq -r '.field.publicId')
	echo PublicID: $publicId
	
	payoutstats=$(curl -s https://field.carriota.com/api/v1/seasons --insecure | jq ".[].payouts[] | select(.publicId==\"$publicId\")")
	#echo $payoutstats
  
    attachToTangle=$(echo $nodestats | jq -r '.workDone.attachToTangle')
    attachToTanglePoints=$((${attachToTangle}*50))
    #echo $attachToTanglePoints

    broadcastTransactions=$(echo $nodestats | jq -r '.workDone.broadcastTransactions')
    broadcastTransactionsPoints=$((${broadcastTransactions}*5))
    #echo $broadcastTransactionsPoints

    checkConsistency=$(echo $nodestats | jq -r '.workDone.checkConsistency')
    checkConsistencyPoints=$((${checkConsistency}*5))
    #echo $checkConsistencyPoints

    findTransactions=$(echo $nodestats | jq -r '.workDone.findTransactions')
    findTransactionsPoints=$((${findTransactions}*5))
    #echo $findTransactionsPoints

    getBalances=$(echo $nodestats | jq -r '.workDone.getBalances')
    getBalancesPoints=$((${getBalances}*3))
    #echo $getBalancesPoints

    getInclusionStates=$(echo $nodestats | jq -r '.workDone.getInclusionStates')
    getInclusionStatesPoints=$((${getInclusionStates}*3))
    #echo $getInclusionStatesPoints

    getNodeInfo=$(echo $nodestats | jq -r '.workDone.getNodeInfo')
    getNodeInfoPoints=$((${getNodeInfo}*1))
    #echo $getNodeInfoPoints

    getTransactionsToApprove=$(echo $nodestats | jq -r '.workDone.getTransactionsToApprove')
    getTransactionsToApprovePoints=$((${getTransactionsToApprove}*3))
    #echo $getTransactionsToApprovePoints

    getTrytes=$(echo $nodestats | jq -r '.workDone.getTrytes')
    getTrytesPoints=$((${getTrytes}*3))
    #echo $getTrytesPoints

    storeTransactions=$(echo $nodestats | jq -r '.workDone.storeTransactions')
    storeTransactionsPoints=$((${storeTransactions}*20))
    #echo $storeTransactionsPoints

    wereAddressesSpentFrom=$(echo $nodestats | jq -r '.workDone.wereAddressesSpentFrom')
    wereAddressesSpentFromPoints=$((${wereAddressesSpentFrom}*5))
    #echo $wereAddressesSpentFromPoints

    echo "Total:   " $((attachToTanglePoints + broadcastTransactionsPoints + checkConsistencyPoints + findTransactionsPoints + getBalancesPoints + getInclusionStatesPoints + getNodeInfoPoints + getTransactionsToApprovePoints + getTrytesPoints + storeTransactionsPoints + wereAddressesSpentFromPoints))
	echo "Payouts:"
	echo $payoutstats | jq -r '.value'
    exit 0
  elif [ "$nodefound" = "1" ];
		then
		echo "${nodename} not found! Is Field running properly on your node?"
		exit 1
	fi
fi
